// import Navbar from '@/Components/Navbar/Navbar'
// import './globals.css'
// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import Footer from '@/Components/Footer'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className='flex flex-col font-DMSans  min-h-screen h-full '>
//         <Navbar/>
//         <main className='flex-1 bg-slate-600 h-full '>
//             {children}
//         </main>
//         <Footer/>
//         </body>
//     </html>
//   )
// }
import Navbar from '@/Components/Navbar/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/Components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body className='flex flex-col font-DMSans min-h-screen h-full  relative'>
        <Navbar  />
        <main className='flex-1 mt-14'>
          <div className='h-full'>{children}</div>
        </main>
        <Footer />
      </body>
    </html>
  )
}
