
import Navbar from "@/Components/Navbar/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/Components/Footer";
import { FilterContextProvider } from "@/context/FilterContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col font-DMSans min-h-screen h-full  relative">
        <Navbar />
        <main className="flex-1 mt-14">
          <div className="h-full">
            <FilterContextProvider>{children}</FilterContextProvider>
          </div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
